from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_pdf(defects: list, heatmap_path: str,
                 output_path: str = "outputs/report.pdf") -> str:
    try:
        doc = SimpleDocTemplate(output_path, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle('Title', fontSize=22, fontName='Helvetica-Bold',
                                     textColor=colors.HexColor('#1E3A5F'), spaceAfter=6)
        story.append(Paragraph("Infrastructure Defect Inspection Report", title_style))

        sub_style = ParagraphStyle('Sub', fontSize=11, textColor=colors.grey, spaceAfter=20)
        story.append(Paragraph(f"Generated: {datetime.now().strftime('%d %B %Y, %I:%M %p')}", sub_style))

        story.append(Spacer(1, 0.1 * inch))

        # Summary
        max_sss = max((d.get("sss", 1) for d in defects), default=1)
        total = len(defects)

        if max_sss <= 2:
            rec = "Structure is safe. Continue routine monitoring."
            rec_color = colors.HexColor('#10B981')
        elif max_sss == 3:
            rec = "Minor defects found. Schedule maintenance."
            rec_color = colors.HexColor('#F59E0B')
        else:
            rec = "Critical defects detected. Immediate action required."
            rec_color = colors.HexColor('#EF4444')

        summary_data = [
            ["Total Defects", "Highest SSS", "Recommendation"],
            [str(total), str(max_sss), rec]
        ]
        summary_table = Table(summary_data, colWidths=[1.5*inch, 1.5*inch, 4*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1E3A5F')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 10),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#F8FAFC')),
            ('TEXTCOLOR', (2,1), (2,1), rec_color),
            ('FONTNAME', (2,1), (2,1), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 0.3 * inch))

        # Heatmap image
        if os.path.exists(heatmap_path):
            story.append(Paragraph("Defect Heatmap", styles['Heading2']))
            img = Image(heatmap_path, width=6*inch, height=3.5*inch)
            story.append(img)
            story.append(Spacer(1, 0.3 * inch))

        # Defect table
        if defects:
            story.append(Paragraph("Defect Details", styles['Heading2']))
            table_data = [["#", "Defect Type", "Confidence", "SSS", "Action"]]
            for i, d in enumerate(defects, 1):
                table_data.append([
                    str(i),
                    d.get("class_name", "unknown"),
                    f"{d.get('confidence', 0):.2%}",
                    str(d.get("sss", 1)),
                    d.get("action", "Monitor Only")
                ])

            defect_table = Table(table_data, colWidths=[0.4*inch, 1.4*inch, 1.1*inch, 0.6*inch, 3*inch])

            # Color SSS column
            table_style = [
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1E3A5F')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('FONTSIZE', (0,0), (-1,-1), 9),
                ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
                ('PADDING', (0,0), (-1,-1), 6),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#F8FAFC')]),
            ]
            for i, d in enumerate(defects, 1):
                sss = d.get("sss", 1)
                if sss <= 2:
                    cell_color = colors.HexColor('#D1FAE5')
                elif sss == 3:
                    cell_color = colors.HexColor('#FEF3C7')
                else:
                    cell_color = colors.HexColor('#FEE2E2')
                table_style.append(('BACKGROUND', (3, i), (3, i), cell_color))

            defect_table.setStyle(TableStyle(table_style))
            story.append(defect_table)

        story.append(Spacer(1, 0.5 * inch))

        # Footer note
        note_style = ParagraphStyle('Note', fontSize=8, textColor=colors.grey, borderPad=4)
        story.append(Paragraph(
            "Generated by SC02 Infrastructure Inspector | Ignisia AI Hackathon | MIT-WPU Pune",
            note_style))
        story.append(Paragraph(
            "⚠️ Note: This report is AI-assisted. Final decisions must be made by a certified structural engineer.",
            note_style))

        doc.build(story)
        print(f"✅ PDF saved → {output_path}")
        return output_path

    except Exception as e:
        print(f"❌ PDF error: {e}")
        return ""
